server:
  port: 8085
hm:
  db:
    database: hm-trade
  swagger:
    title: "QQ商城交易服务接口文档"
    package: com.qiu.trade.controller
spring:
  rabbitmq:
    host:
    port: 5672
    virtual-host: /hmall
    password: 123
    username: hmall