server:
  port: 8082
  tomcat:
    threads:
      max: 25   #允许最大线程
    accept-count: 25  #线程占满后排队等待的线程数
    max-connections: 100
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    database: hm-cart
  swagger:
    title: "QQ商城购物车服务接口文档"
    package: com.qiu.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090   #sentinel的控制台地址
      http-method-specify: true     #开启请求方式前缀,设置请求方式作为资源名称

